Support fusion engine output in sbp2nmea
swift-nav/gnss-converters pull request #494
Opened 2020-09-08 05:41 UTC by woodfell

2020-09-08 06:50 UTC, benjaminaltieri requested changes
This is great, looks exactly like the potential changes the output refactor for the fusion engine would enable. Ironically (or not) main bone to pick here is on naming/spelling which I would prefer not to canonize. Otherwise would have approved. Rest of the comments questions are there for your consideration. Overall awesome work on this :+1:

2020-09-08 06:50 UTC, benjaminaltieri commented on c/include/gnss-converters/sbp_nmea.h
> +  SBP2NMEA_MODE_FUZED,
Let's avoid the 'z', although there seems to be some uptake in this alternative spelling: fusion, fuse and fused are more directly recognizable as correct spelling/conjugation

2020-09-08 06:50 UTC, benjaminaltieri commented on c/include/gnss-converters/sbp_nmea.h
> -void sbp2nmea_soln_freq_set(sbp2nmea_t *state, float soln_freq);
This may have implications on the use case in Piksi, updating the solution frequency while running may needs to be a supported use case but I can't remember exactly how it is used atm

2020-09-08 06:50 UTC, benjaminaltieri commented on c/src/gnss_converters/sbp_nmea.c
> +
Whitespace

2020-09-08 06:50 UTC, benjaminaltieri commented on c/src/gnss_converters/sbp_nmea.c
> +    if (group_meta->group_id == 2) {
Is this actually functional yet? Nice to have a call out for the future, would be better to use a define that indicate what 2 means here (implicit from the resulting execution but might not be for others in the future)

2020-09-08 06:50 UTC, benjaminaltieri commented on c/src/gnss_converters/sbp_nmea.c
> +  if (msg_type == SBP_MSG_GROUP_META) {
It would be helpful to have a bit more structure to this block, there a couple things going on including checking for complete wagons and switching modes.  A clear definition of how the fusion wagon is determined complete looks now to be has a solution meta message been received following a group meta message. My understanding (this may be for future improvement) was that the group meta had everything needed to verify proper receipt of the group but it isn't used here.

2020-09-08 06:50 UTC, benjaminaltieri commented on c/src/gnss_converters/sbp_nmea.c
> +    if (state->requested_mode == SBP2NMEA_MODE_BEST &&
Should we make sure the group meta is not a GNSS group, as implemented above?

2020-09-08 06:54 UTC, woodfell commented on c/include/gnss-converters/sbp_nmea.h
> +  SBP2NMEA_MODE_FUZED,
Oh I'm so glad someone else said that :smile: I though 'z' was an American thing and I was just going to have to go with it

2020-09-08 06:55 UTC, woodfell commented on c/include/gnss-converters/sbp_nmea.h
> -void sbp2nmea_soln_freq_set(sbp2nmea_t *state, float soln_freq);
Yeah now you mention it it does need to be updated in real time. I'll put the "set" functions back in

2020-09-08 06:55 UTC, woodfell commented on c/src/gnss_converters/sbp_nmea.c
> +    if (group_meta->group_id == 2) {
No idea. I saw it in the struct definition so went with it. Haven't seen it actually be used in testing though. I'll get rid of it for the moment.

2020-09-08 06:59 UTC, benjaminaltieri commented on c/include/gnss-converters/sbp_nmea.h
> +  SBP2NMEA_MODE_FUZED,
I was thinking of the irony, that this is the one 'z' you didn't rebel against :joy:

2020-09-08 08:22 UTC, woodfell commented on c/src/gnss_converters/sbp_nmea.c
> +  if (msg_type == SBP_MSG_GROUP_META) {
Reworked it a little, split some stuff out to separate functions. Hopefully reads a bit better now. 

Also added some state information to keep track of the fused wagon. It will be marked as complete once all messages have been received rather than when SOLN_META is received (although in practice these are the same). Waiting to hear back about the contents of `group_msgs` in `GROUP_META` - the comments in libsbp suggest that `GROUP_META` itself should be a member of that array but in the SBP log I'm testing with it isn't.

2020-09-08 08:23 UTC, woodfell commented on c/src/gnss_converters/sbp_nmea.c
> +    if (state->requested_mode == SBP2NMEA_MODE_BEST &&
Is this still relevant?

2020-09-09 16:30 UTC, anth-cole approved these changes
lgtm

2020-09-28 04:56 UTC, closed without merging